name: WakaTime Stats

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12 PM UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
